allowBuilds:
  esbuild: true
  msgpackr-extract: false
  sharp: set this to true or false
  unrs-resolver: set this to true or false
ignoredBuiltDependencies:
  - msgpackr-extract
  - sharp
  - unrs-resolver
