import type { PageSnapshot } from "@/lib/extraction/schemas";

export function createMockSnapshot(overrides?: Partial<PageSnapshot>): PageSnapshot {
  return {
    schemaVersion: "1.0.0",
    extractedAt: new Date().toISOString(),
    requestedUrl: "https://example.com/page",
    finalUrl: "https://example.com/page",
    response: {
      status: 200,
      contentType: "text/html",
      byteLength: 5000,
      redirectChain: [],
      timing: { dns: 10, connect: 20, tls: 5, firstByte: 100, total: 200 },
    },
    document: {
      url: "https://example.com/page",
      lang: "en",
      dir: null,
      title: "Test Page Title",
      titleElementCount: 1,
      charsetDeclarations: [{ raw: "utf-8", normalized: "utf-8", elementOrder: 1 }],
      viewportDeclarations: [],
      baseHref: null,
      hasBody: true,
      hasHead: true,
      approxDomNodeCount: 200,
      declaredLanguage: "en",
    },
    metadata: [],
    headings: [],
    links: [],
    images: [],
    structuredData: [],
    microdata: { present: false, itemCount: 0, itemTypes: [] },
    rdfa: { present: false, typeofCount: 0, propertyCount: 0 },
    social: { openGraph: [], twitter: [] },
    content: {
      visibleText: "Hello world this is test content.",
      totalChars: 35,
      wordCount: 7,
      paragraphCount: 1,
      sentenceCount: 2,
      listCount: 0,
      listItemCount: 0,
      tableCount: 0,
      blockquoteCount: 0,
      codePreCount: 0,
      hasMain: true,
      articleCount: 0,
      sectionCount: 0,
      navCount: 0,
      headerCount: 0,
      footerCount: 0,
      asideCount: 0,
      addressCount: 0,
      timeElements: [],
      questionHeadingCount: 0,
      isTruncated: false,
    },
    accessibility: {
      documentLanguage: "en",
      imageAltPresent: { total: 0, withAlt: 0, withoutAlt: 0 },
      formLabelRelationships: { total: 0, withLabel: 0, withoutLabel: 0 },
      inputAccessibleNames: { total: 0, withName: 0, withoutName: 0 },
      buttonTextSignals: { total: 0, withText: 0, withoutText: 0 },
      linkAccessibleNames: { total: 0, withName: 0, withoutName: 0 },
      landmarkElements: { nav: 0, header: 0, footer: 0, aside: 0, main: 1, section: 0 },
      headingElements: { total: 0 },
      skipLinkCandidates: [],
      tableHeaderCells: { totalTh: 0 },
      ariaAttributes: { total: 0, roles: [] },
      duplicateIds: [],
      tabindexValues: [],
      iframeTitles: { total: 0, withTitle: 0, withoutTitle: 0 },
      mediaCaptions: { total: 0, withTrack: 0, withoutTrack: 0 },
      viewportZoomRestricted: false,
    },
    forms: { formCount: 0, forms: [] },
    resources: [],
    extractionWarnings: [],
    ...overrides,
  };
}
